### ISSUE TITLE
Import UV data from an API and use in daily morning TTS to warn for sunscreen

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#13]
https://uvimate.herokuapp.com/blog/2016/12/15/uvindex-open-api/

**Comment by Norien** [comment]
Using rest sensor I was successful in importing local UV index data into home assistant.

https://github.com/Norien/Home-Assistant-Config/blob/master/packages/weather.yaml

**Comment by CCOSTAN** [comment]
This should definitely be a component.  (The UV stuff)..   Great Job with it!
