### ISSUE TITLE
Setup and Deploy SkullCanyon NUC

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#143]
Install new skull canyon nuc
- ~~remove old amd pc ( kodi box )~~
- ~~migrate home assistant~~
- ~~remove old lanparty system~~
- ~~rework pc switch using sonoff dual for tv / amp power~~
- ~~Install new 8TB external HDD and transfer video files onto it. Setup SMB share for windows.~~
- ~~Install and partition 1TB USB HDD / Half for zoneminder and half for rsnapshot backups~~
- ~~Setup automatic rsnapshot backup to USB partition~~
- Update readme

Manual setups:
~~smb~~
~~duckdns~~
~~letsencrypt~~
~~backup mounts~~
~~mosquitto~~
~~mysql~~
~~pihole~~
~~hassctl~~
~~sudoers file~~
  -zwave/zigbee usb mount
  -~~zoneminder~~
  -~~plex media server~~
~~kodi ( frontend )~~
  -~~autostart~~
  -~~netflix addon~~
  -~~STEAM BPM~~
  -~~retro-pie with kodi launcher~~
  -google play music addon ( errors out )

**Comment by Norien** [comment]
# HOME ASSISTANT
#### DEPENDENCIES
```$ sudo apt update```
```$ sudo apt-get upgrade```
```$ sudo apt-get install python 3.6.1```
```$ sudo apt install python3-dev python3-pip```
```$ sudo pip3 install --upgrade virtualenv```
```$ pip3 install --upgrade virtualenv```
```$ sudo apt-get install python3-venv```
#### EXTRA DEPENDENCIES
```$ sudo apt-get install net-tools nmap```
```$ sudo apt-get install libudev-dev```
```$ sudo apt-get install ssl-cert-check```

#### USERS/GROUPS
```$ sudo adduser --system homeassistant```
```$ sudo addgroup homeassistant```
```$ sudo adduser homeassistant dialout```

#### FOLDERS AND PERMISSIONS
```$ sudo mkdir /home/homeassistant/.homeassistant```
```$ sudo chown homeassistant:homeassistant /home/homeassistant/.homeassistant```
```$ sudo mkdir /srv/homeassistant```
```$ sudo chown homeassistant:homeassistant /srv/homeassistant```

#### SWITCH USER
```$ sudo su -s /bin/bash homeassistant```

#### DO THE INSTALL
```$ cd /srv/homeassistant```
```$ python3 -m venv /srv/homeassistant```
```$ source bin/activate```
```$ pip3 install --upgrade homeassistant```

#### AUTOSTART
```$ sudo nano /etc/systemd/system/home-assistant.service```

#### ADD THIS------------- AND SAVE
```
[Unit]
Description=Home Assistant
After=network.target mosquitto.service

[Service]
ExecStart=/srv/homeassistant/bin/hass -c "/home/homeassistant/.homeassistant"
Type=simple
User=homeassistant
ExecReload=/srv/homeassistant/bin/hass -c "$HASS_CONFIG" --script check_config
ExecReload=/bin/kill -HUP $MAINPID
SendSIGKILL=yes
TimeoutStopSec=15

[Install]
WantedBy=multi-user.target
```
#### ENABLE SERVICE
```$ sudo systemctl enable home-assistant.service```
```$ sudo systemctl --system daemon-reload```
```$ sudo systemctl start home-assistant.service```

# HASSCTL
```$ sudo curl -o /usr/local/bin/hassctl https://raw.githubusercontent.com/dale3h/hassctl/master/hassctl && sudo chmod +x /usr/local/bin/hassctl```
### GIVE HASSCTL SUDO
```$ sudo visudo```
### AND ADD TO BOTTOM 
```$ homeassistant ALL=(ALL) NOPASSWD: /usr/local/bin/hassctl```

# MySQL DB
CREDIT** https://github.com/brianjking/homeassistant-config/blob/master/docs/mysql.md
```$ sudo apt-get update && sudo apt-get upgrade```  
```$ sudo apt-get install mysql-server && sudo apt-get install mysql-client```  
```$ sudo apt-get install libmysqlclient-dev```  
```$ sudo apt-get install python-dev python3-dev```  
```$ mysql -uroot -p```  
```$ CREATE DATABASE dbname;```  
```$ CREATE USER 'dbuser'@'localhost' IDENTIFIED BY 'password';```  
```$ GRANT ALL PRIVILEGES ON dbname.* TO 'dbuser'@'localhost';```  
```$ FLUSH PRIVILEGES;```  

**Test if user works:**  
```$ mysql -u dbuser dbname -p```

**Switch to HASS env**  

```$ sudo su -s /bin/bash homeassistant```
```$ source /srv/homeassistant/bin/activate```
```$ pip3 install --upgrade mysqlclient```  

**Add to configuration.yaml**  
```yaml
recorder:
  db_url: mysql://dbuser:password@localhost/dbname
```

# MOSQUITTO
```$ sudo apt-get install mosquitto```
```$ sudo apt-get install mosquitto-clients```

```$ sudo nano /etc/mosquitto/mosquitto.conf```

```
allow_anonymous false
password_file /etc/mosquitto/pwfile
listener 1883
```

```$ sudo mosquitto_passwd -c /etc/mosquitto/pwfile username```
### TESTING
```$ mosquitto_sub -d -u username -P password -t "dev/test"```
```$ mosquitto_pub -d -u username -P password -t "dev/test" -m "Hello world"```

# HTTPS/SSL/DUCKDNS
https://www.splitbrain.org/blog/2017-08/10-homeassistant_duckdns_letsencrypt

# RSNAPSHOT BACKUP
https://blog.ceard.tech/2017/10/backing-up-home-assistant.html

**Comment by B3voholic** [comment]
Installing the current version of Plex Media Server

```
$ wget https://downloads.plex.tv/plex-media-server/1.10.1.4602-f54242b6b/plexmediaserver_1.10.1.4602-f54242b6b_amd64.deb
$ sudo dpkg -i plexmediaserver*.deb

$ sudo systemctl enable plexmediaserver.service
$ sudo systemctl --system daemon-reload
$ sudo systemctl start plexmediaserver.service
```

You can get the link for the current version of Plex from their downloads page.

**Comment by B3voholic** [comment]
Installing Glances.

```
$ sudo apt-get install glances

Create the service file.
$ sudo nano /etc/systemd/system/glances.service

Add the following to the file.

[Unit]
Description=Glances

[Service]
ExecStart=/usr/bin/glances -w
Restart=on-abort

[Install]
WantedBy=multi-user.target

Exit and save the file by pressing Ctrl+X, then Y, then Enter

$ sudo systemctl enable glances.service
$ sudo systemctl --system daemon-reload
$ sudo systemctl start glances.service
