### ISSUE TITLE
Guard Dog

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#16]
perfect for when doorbell is pushed & away or vacation mode is on
https://github.com/CCOSTAN/Home-AssistantConfig/issues/96

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/sounds/dog-barking-2-bullmastiff.mp3
https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/sounds/german-shephard.mp3

**Comment by CCOSTAN** [comment]
I went with the Bull Mastiff. :)

**Comment by CCOSTAN** [comment]
Just realized today that a snooze is needed if hooked to the front door. Quick way to tell Alexa to silence the dogs for a time period.

**Comment by Norien** [comment]
Also need to make sure if doorbell is pressed twice in a row I won't get 2 notifications and the mp3 won't start then stop then start

**Comment by CCOSTAN** [comment]
That's a really easy one to solve.  I just disable the automation for 1 minute.

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/automation/dash_buttons.yaml#L10-L19

**Comment by Norien** [comment]
Guard dog is working if doorbell is pressed and nobody is home

https://github.com/Norien/Home-Assistant-Config/blob/master/packages/doorbell.yaml

Just have to add Media player volume set so it's max
