### ISSUE TITLE
ClearOne XAP800

### ISSUE THREAD

**Issue by thebradleysanders** [Norien/Home-Assistant-Config#195]
I discovered your repo and saw the ClearOne XAP800, what is your intended purpose for this?
Please explain, I was thinking it may have the potential to be a cheap multiroom audio solution.

**Comment by Norien** [comment]
My first thought was to use with my surround sound receiver and a chrome cast audio so I can have TTS notifications and doorbell sounds run on top of television/movies/music playing in the living room

**Comment by thebradleysanders** [comment]
I see, that's also a good idea, as cheap as they have gotten it would be a great multi-room audio/intercom solution, it seems to have a serial interface, this could be controlled with an esp8266 or other arduino based boards, this controller also supports grouping also exposed to the serial port, I was not familiar with this product so thanks for sharing and responding back to me.
