### ISSUE TITLE
HA 0.87 is breaking your Home-Assistant-Config/packages/vacuum.yaml

### ISSUE THREAD

**Issue by ddppddpp** [Norien/Home-Assistant-Config#199]
Apparently there's something wrong with the way 0.87 interprets your vacuum package.
Been borrowing this code for it for a couple of weeks till I get around setting up a custom component :-) anyway:
[sensor.mqtt]: [type] is an invalid option for [sensor.mqtt]
which I believe is related to the following code
` - platform: mqtt
    name: roomba_last_run
    state_topic: "homeassistant/vacuum"
    type: time
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'`
Are you seeing the same error msg?

**Comment by Norien** [comment]
fixed here, sorry just saw this now :) cheers 

https://github.com/Norien/Home-Assistant-Config/commit/ca2d80a264488eaf0d8b42fdc5ef68874e4a5b56
