### ISSUE TITLE
Just a note on the roomba package

### ISSUE THREAD

**Issue by riemers** [Norien/Home-Assistant-Config#201]
I made mine based on yours. https://github.com/riemers/home-assistant-config/blob/master/extraconfig/packages/roomba.yaml 

The only thing i did add was a history how much it ran for 1 day. So if you come and go constantly it would trigger it again and again. With the daily one it checks if it has ran for more then an hour. If so don't retrigger. (presume it works, hard to test ha) but you get the idea.

**Comment by Norien** [comment]
Thanks! I think it all looks good, I don't mind my roomba running all day if we are out, usually someone is home anyways :) cheers!

**Comment by riemers** [comment]
Ah ok, then the watchdog makes sense for your:)

**Comment by Norien** [comment]
thanks for helping me test my compact-custom-header template haha
```
        conditional_styles:
          template:
            - tab:
                1:
                - icon: >
                    if (states["sensor.home_assistant_config_issues"].state == "0") "mdi:death-star";
                    else "mdi:death-star-variant";
```
May the force be with you!

**Comment by riemers** [comment]
Looks like another one for my copy paste actions ;)

Copying all the gems, keep first line as place where i found it..

I do like my New automation. Alert me on the speakers if I am home if the wife is in the supermarket (so I can still call her for something nice to bring along)
