### ISSUE TITLE
Add jungle live scene

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#22]
https://youtu.be/8myYyMg1fFE
![capture](https://cloud.githubusercontent.com/assets/8930713/25715482/9f6787ac-30c9-11e7-94c5-0e9e48fd66e6.PNG)

**Comment by CCOSTAN** [comment]
Are you going to make this a 3 hour MP3?

**Comment by Norien** [comment]
I rip the video and convert it to MP4. Then I take a screenshot.

If you import the screenshot Into Philips hue app it sets a scene based off the colours.

My live scene scripts basically set the correct light scene and play the video. I decided to keep video local for super fast load time and to keep internet usage lower over time. 
https://github.com/Norien/Home-Assistant-Config/blob/master/packages/live_scenes.yaml

**Comment by Norien** [comment]
https://github.com/Norien/Home-Assistant-Config/blob/master/packages/live_scenes.yaml
