### ISSUE TITLE
Implement restart counter 

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#24]
Credit to @brahmafear
https://github.com/brahmafear/hass_config/blob/master/yaml/packages/hass.yaml#L19

**Comment by CCOSTAN** [comment]
I think this will help you.  https://home-assistant.io/components/sensor.history_stats/

**Comment by Norien** [comment]
Thanks @CCOSTAN that worked well with addition of an input boolean.
![capture](https://cloud.githubusercontent.com/assets/8930713/25715764/ab569750-30ca-11e7-8ac7-7d30c890b3fc.PNG)
