### ISSUE TITLE
Full image backup of homeserver

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#9]
Create a disk image for home server and store on smb share

**Comment by Norien** [comment]
Using Reflect to backup full image to my windows share

**Comment by CCOSTAN** [comment]
Do you have a link for this?  Does reflect create live running backups?

**Comment by Norien** [comment]
https://www.macrium.com/reflectfree

I've used this program for a few years now to backup several windows based systems without fail. I thought I would give it a try for Ubuntu.

This isn't a live backup. I had to physically pull the drive and bring it to a laptop which was running reflect. 

I happen to have two of the same hard drives so my plan is to :

- Pull drive and create image
- save image to smb share
- reimage 2nd drive
- install 2nd drive to homeserver 
- check everything is fine and dandy. 

Last night after doing this the homeserver did not boot. It was late so I installed the original drive and everything came back ok.

I think possibly there is something wrong with my USB to SATA board or possibly my laptop's USB port is a little too worn out. Later today I will attempt a second image but this time connect server hard drive directly into my gaming desktop via SATA.

The idea is to setup some sort of redundant drive system where I can pull one at any time and make a disk image.

**Comment by Norien** [comment]
I have a bit of time to bring the server down, Attempting another full image backup connected to SATA via windows using reflect! I will try and copy the image to a 2nd ( same size drive ) and boot from the backup to confirm the image was created successfully

**Comment by Norien** [comment]
I failed once again. Here is what I did
- removed running OS and installed SATA to my windows box 
- created image using reflect and stored on backup drive
- used the new image to restore a spare drive ( exact same make/model and size )
- reinstalled newly imaged drive to server
- NO Boot. comes to grub rescue screen.

ok so maybe it's because I did this inside windows...

- install running OS SATA to windows box ( again )
- boot to reflect recovery USB environment 
- create new image
- install spare drive and load the new created image
- again no boot, grub rescue screen.

I have run out of time to try another method but looks like reflect is NOT the answer i'm looking for.

**Comment by Norien** [comment]
Backup Routine in place thanks to @tinkerer - https://blog.ceard.tech/2017/10/backing-up-home-assistant.html
